# This is a basic workflow to help you get started with Actions

name: test

on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build and test
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
        with:
          args: test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: build/test-results/**/*.xml